name: PipelineWorkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
    build:
        name: Azure Pipeline
        runs-on: window-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/user477047/Agile-process
            azure-pipeline-name: 'Devopsproject4770.gitapp2'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}